add vagrant post smoke test

diff --git a/test.sh.in b/test.sh.in
--- a/test.sh.in
+++ b/test.sh.in
@@ -392,6 +392,33 @@ if [ "$RUN_CIT_TEST" == true ] || [ "$RUN_FIT_TEST" == true ] ; then
     #shutdown vagrant box and delete all resource (like removing vm disk files in "~/VirtualBox VMs/")
     #cleanupVMs
     #nodesDelete
+  elif [ "$TEST_TYPE" == "vagrant" ]; then
+    # register the signal handler to clean up( vagrantDestroy ), with process being killed
+    trap cleanupVMs SIGINT SIGTERM SIGKILL
+    cleanupVMs
+
+    # based on the assumption that in the same folder, the VMs has been exist normally. so don't destroy VM here.
+    
+    nodesCreate
+    # We setup the virtual-environment here, since once we
+    # call "nodesOn", it's a race to get to the first test
+    # before the nodes get booted far enough to start being
+    # seen by RackHD. Logically, it would be better IN runTests.
+    # We do it between the vagrant and waitForAPI to use the
+    # time to make the env instead of doing sleeps...
+    setupVirtualEnv
+    waitForAPI
+    nodesOn &
+    generateSolLog
+    # Run tests
+    runTests
+    generateSysLog
+
+    # Clean Up below
+
+    #shutdown vagrant box and delete all resource (like removing vm disk files in "~/VirtualBox VMs/")
+    #cleanupVMs
+    #nodesDelete
   else
     # rese the UCSPE emulators 
     ucsReset
